repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    language_version: python3
    language: system
- repo: https://github.com/pycqa/pylint
  rev: v3.0.3
  hooks:
  - id: pylint
    args: [--rcfile=toolscfg/pylintrc]
    language: system
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    args: [--config-file=toolscfg/mypy.ini]
    language: system
